apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hazelcast-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hazelcast-demo
    spec:
      containers:
        - name: hazelcast-demo
          image: 'shahaf255/hazelcast-demo:0.0.6-SNAPSHOT'
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-demo-service
  labels:
    name: hazelcast-demo-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: hazelcast-demo
  type: LoadBalancer
